#!/usr/bin/env ruby

require "json"
require "common"

config = find_config(ARGV[1])
strings = find_strings(ARGV[0], config)

for string in strings

	string_text = string[1].to_json

	if string[1] == nil
		string_text = "NULL"
	end

	printf "    { %6i, %s },\n", string[0], string_text
end

